package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// The term file holds the maintained list outside config.yaml, one entry per
// line, so a long list of hostnames stays editable and can be generated by
// cmd/termsgen. Two line forms are accepted and may be mixed:
//
//	p14.local                      literal, kind host
//	p14.local host                 literal with kind
//	markus person ignore_case      literal with kind and the case flag
//	{regex: "[a-z]+\\.home\\.lan", kind: host}
//	{value: "wendler.de", kind: domain}
//
// A line starting with "{" is a YAML flow mapping with the same keys as a
// terms[] entry in config.yaml. A "#" at the start of a line or after white
// space opens a comment; a "#" inside a word belongs to the value, so
// Projekt#42 is one term and not a truncated one. Blank lines are skipped,
// and a byte order mark ahead of the first line is dropped. A line of the
// first form is split on white space: the first word is the literal, the
// optional second word the kind, and the optional word ignore_case sets the
// flag. A literal that needs spaces, that starts with "{" or "#", or that
// carries a "#" behind a space goes into the YAML form.

// termsFileDefaultKind applies when a plain line names no kind.
const termsFileDefaultKind = "host"

// resolveTermsFilePath returns the absolute path of the term file. A relative
// value resolves against pluginDir, like gitleaks_toml and salt_secret_path.
// An empty value means no file.
func resolveTermsFilePath(pluginDir, configured string) string {
	if configured == "" {
		return ""
	}
	if filepath.IsAbs(configured) {
		return configured
	}
	return filepath.Join(pluginDir, configured)
}

// loadTermsFile reads the term file at path. It returns an error for an
// unreadable file or an invalid line, naming the line number, so a plugin in
// pseudonymize mode refuses to start with half a list rather than silently
// scanning with the other half.
func loadTermsFile(path string) ([]TermEntry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	entries, err := parseTermsFile(f)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return entries, nil
}

// parseTermsFile parses the term file format described above.
func parseTermsFile(r io.Reader) ([]TermEntry, error) {
	var entries []TermEntry
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := sc.Text()
		if lineNo == 1 {
			// An editor on Windows writes a byte order mark ahead of the
			// first line. TrimSpace does not remove it, so without this the
			// first term of the list is a different string from the one the
			// user typed and protects nothing. Written as its three bytes
			// because the compiler rejects the character itself in source.
			line = strings.TrimPrefix(line, "\xef\xbb\xbf")
		}
		line = strings.TrimSpace(stripTermsComment(line))
		if line == "" {
			continue
		}
		entry, err := parseTermsLine(line)
		if err != nil {
			return nil, fmt.Errorf("line %d: %w", lineNo, err)
		}
		entries = append(entries, entry)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

// stripTermsComment removes a comment from one line. A '#' opens a comment
// only at the start of a line or after white space, so a term that carries a
// '#' inside its value - Projekt#42, a ticket number, a fragment of a URL -
// is loaded whole. Cutting at every '#' would load such a term truncated and
// leave the part behind the '#' unprotected, which is the opposite of what
// the list is for. A line in the YAML form keeps its '#', because there a
// quoted value may hold one.
func stripTermsComment(line string) string {
	if strings.HasPrefix(strings.TrimSpace(line), "{") {
		return line
	}
	for i := 0; i < len(line); i++ {
		if line[i] != '#' {
			continue
		}
		if i == 0 || line[i-1] == ' ' || line[i-1] == '\t' {
			return line[:i]
		}
	}
	return line
}

// parseTermsLine parses one non-empty, trimmed line.
func parseTermsLine(line string) (TermEntry, error) {
	if strings.HasPrefix(line, "{") {
		var entry TermEntry
		dec := yaml.NewDecoder(strings.NewReader(line))
		dec.KnownFields(true)
		if err := dec.Decode(&entry); err != nil {
			return TermEntry{}, fmt.Errorf("invalid entry %q: %w", line, err)
		}
		if entry.Kind == "" {
			entry.Kind = termsFileDefaultKind
		}
		return entry, nil
	}

	fields := strings.Fields(line)
	entry := TermEntry{Value: fields[0], Kind: termsFileDefaultKind}
	kindSet, flagSet := false, false
	for _, opt := range fields[1:] {
		switch {
		case opt == "ignore_case" && !flagSet:
			entry.IgnoreCase = true
			flagSet = true
		case !kindSet && !flagSet && !strings.ContainsAny(opt, "{}:,"):
			entry.Kind = opt
			kindSet = true
		default:
			return TermEntry{}, fmt.Errorf("unexpected word %q in %q (want: <literal> [kind] [ignore_case])", opt, line)
		}
	}
	return entry, nil
}

// mergeTerms appends the file entries to the inline list and drops exact
// duplicates, keeping the first occurrence. Two entries are duplicates when
// value, regex, kind and ignore_case all match; the same literal under two
// kinds is kept twice on purpose, and detect.Merge lets the longer or earlier
// hit win.
func mergeTerms(inline, file []TermEntry) []TermEntry {
	out := make([]TermEntry, 0, len(inline)+len(file))
	seen := make(map[TermEntry]bool, len(inline)+len(file))
	for _, list := range [][]TermEntry{inline, file} {
		for _, t := range list {
			if seen[t] {
				continue
			}
			seen[t] = true
			out = append(out, t)
		}
	}
	return out
}
